AWSTemplateFormatVersion: "2010-09-09"
Description: "Binance Ticker prices"
Resources:
    DynamoDBTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "symbol"
                AttributeType: "S"
              - 
                AttributeName: "timestamp"
                AttributeType: "N"
            BillingMode: "PAY_PER_REQUEST"
            TableName: "binance-prices"
            KeySchema: 
              - 
                AttributeName: "symbol"
                KeyType: "HASH"
              - 
                AttributeName: "timestamp"
                KeyType: "RANGE"
            TimeToLiveSpecification:
              AttributeName: "ttl"
              Enabled: true


